- tsconfig.json
- yarn.lock
Deskripsi:
- pengaturan folder
No Issues
> folder manager:

- package.json
- prisma/schema.prisma
- yarn.lock
Deskripsi:
- pembuatan struktur database awal
- nambah folder village
- ganti nama folder discuss menjadi discussion
No Issues
> database awal

- package.json
- yarn.lock
Deskripsi:
- install hookstate
No Issues
> install package

- src/module/group/components/list_group_active.tsx
- src/module/group/components/list_group_non_active.tsx
- src/module/group/components/tab_list_group.tsx
- src/module/group/components/ui/edit_drawer_group.tsx
- src/module/group/components/ui/navbar_group.tsx
- src/module/group/view/view_group.tsx
Deskripsi:
-update list group
- update edit drawer group
- navbar group
- view group
No Issue
> style : add group

- src/module/_global/index.ts
- src/module/_global/layout/layout_drawer.tsx
- src/module/_global/layout/layout_navbar_home.tsx
- src/module/_global/layout/layout_navbar_new.tsx
- src/module/announcement/component/ui/navbar_announcement.tsx
- src/module/auth/welcome/view_welcome.tsx
Deskripsi:
- update maxsidth drawer
- update maxwidth welcome page
- membuat drawer baru
No Issues
> upd: tampilan

- src/module/home/components/list_divisi.tsx
- src/module/home/components/list_project.tsx
Deskripsi:
- pengaplikasian caraousel pada list proyek dan divisi
No Issues
> upd: beranda

- src/app/(application)/(detail-division)/task/create/page.tsx
- src/app/(application)/(detail-division)/task/update/[id]/page.tsx
- src/app/(application)/project/create/page.tsx
- src/app/(application)/project/update/[id]/page.tsx
- src/module/division_new/_division_fitur/task/component/create_task.tsx
- src/module/division_new/_division_fitur/task/view/view_create_division_task.tsx
- src/module/division_new/index.ts
- src/module/project/components/create_date_end_task.tsx
- src/module/project/components/create_users_project.tsx
- src/module/project/components/detail_project/detail_create_user_project.tsx
- src/module/project/components/detail_project/detail_date_end_task.tsx
- src/module/project/components/detail_project/detail_project.tsx
- src/module/project/components/detail_project/file_upload_progres.tsx
- src/module/project/components/detail_project/update_progres.tsx
- src/module/project/components/file_save.tsx
- src/module/project/view/view_file_save.tsx
Deskripsi:
- tambah task divisi
- perbaiki routing update progress project
No Issues
> upd: task division

- src/module/division_new/components/detail_division/detail_division.tsx
- src/module/division_new/components/detail_division/list_task.tsx
Deskripsi:
- tambah list tugas hari ini
No Issues
> upd: detail divsi

- src/module/division_new/components/detail_division/detail_division.tsx
- src/module/division_new/components/detail_division/list_document.tsx
Deskripsi:
- nambah list dokumen terbaru pada halaman detail divisi
No Issues
> upd: detail divisi

- src/module/division_new/_division_fitur/document/components/ui/drawer_copy_documents.tsx
- src/module/division_new/_division_fitur/document/components/ui/drawer_cut_documents.tsx
- src/module/division_new/_division_fitur/document/components/ui/drawer_more.tsx
- src/module/division_new/_division_fitur/document/components/ui/navbar_document_division.tsx
Deskripsi:
- add copy data
- acut data
- more
No Issue
> style : add documets

- src/module/user/member/component/edit_member.tsx
- src/module/user/member/component/list_member.tsx
- src/module/user/member/component/ui/drawer_detail_member.tsx
- src/module/user/member/component/ui/navbar_detail_member.tsx
- src/module/user/member/component/ui/tab_list_member.tsx
- src/module/user/member/view/view_detail_member.tsx
Deskripsi:
- tab status member
- edit form
- informasi gender
No Issues
> upd: member

- src/module/_global/layout/layout_navbar_new.tsx
- src/module/division_new/components/ui/navbar_detail_division.tsx
Deskripsi:
- update ukuran text title navbar
No Issues
> upd: navbar

- prisma/schema.prisma
- prisma/seed.ts
- src/module/seeder/data/admin.json
- src/module/seeder/data/admin_role.json
- src/module/seeder/data/desa.json
- src/module/seeder/data/group.json
- src/module/seeder/data/position.json
- src/module/seeder/data/user.json
- src/module/seeder/data/user_role.json
- src/module/seeder/index.ts
- src/module/user/api/get/getAllUser.ts
Deskripsi:
- update struktur database
- tambah table admin dan role admin
- update seeder
No Issues
> upd: update struktur database

- src/module/group/api/get/listGroup.ts
- src/module/group/components/list_group_active.tsx
- src/module/position/api/get/getAllPosition.ts
- src/module/position/component/ui/list_position_active.tsx
- src/module/user/api/get/getAllUser.ts
- src/module/user/member/component/list_member.tsx
- src/module/user/member/component/ui/tab_list_member.tsx
Deskripsi:
- search group
- search position
- search member / user / anggota
No Issue
> feat : update search

- package.json
- prisma/schema.prisma
- src/app/api/task/route.ts
- src/module/_global/fun/upload-file.ts
- src/module/_global/index.ts
- src/module/task/lib/api_task.ts
- src/module/task/lib/type_task.ts
- src/module/task/ui/create_task.tsx
- src/module/task/ui/list_division_task.tsx
- src/module/task/ui/results_file.tsx
- yarn.lock
Deskripsi:
- tambah dropzone
- update struktur database
- create task
No Issuess
> upd: tambah task divisi

- src/app/(application)/division/[id]/(fitur-division)/task/edit/[detail]/page.tsx
- src/app/api/task/[id]/route.ts
- src/app/api/task/detail/[id]/route.ts
- src/app/api/task/route.ts
- src/module/task/index.ts
- src/module/task/lib/api_task.ts
- src/module/task/lib/val_task.ts
- src/module/task/ui/detail_list_tugas_task.tsx
- src/module/task/ui/detail_progress_task.tsx
- src/module/task/ui/edit_detail_task.tsx
- src/module/task/ui/navbar_detail_division_task.tsx
Deskripsi:
- update task divisi
- delete detail task
- update status task
- edit detail task
No Issues
> upd: task divisi

- src/app/api/document/route.ts
- src/module/document/lib/type_document.ts
- src/module/document/ui/navbar_document_division.tsx
Deskripsi:
- jalur share
- action document yg di share
No Issues
> upd: document

- src/module/position/lib/val_posisition.ts
- src/module/position/ui/drawer_list_position.tsx
- src/module/position/ui/list_position_active.tsx
Deskripsi:
- refresh otomatis
No Issues
> upd: position

- src/app/api/calender/route.ts
- src/module/calender/ui/create_user_calender.tsx
- src/module/calender/ui/date_event_division.tsx
- src/module/calender/ui/navbar_create_division_calender.tsx
- src/module/calender/ui/update_list_users.tsx
- src/module/user/member/ui/create_member.tsx
- src/module/user/member/ui/edit_member.tsx
- src/module/user/member/ui/navbar_detail_member.tsx
- src/module/user/member/ui/tab_list_member.tsx
Deskripsi:
- update tambah anggota
- update list anggota
- update tambah kalender
- update kalender name indonesia
No Issue
> feat : update revisi

- src/app/api/home/route.ts
- src/module/home/ui/chart_document.tsx
- src/module/home/ui/chart_progress_tugas.tsx
Deskripsi:
- belm selesai nih
No Issues
> upd: chart home

- src/app/api/division/[id]/detail/route.ts
- src/app/api/home/route.ts
- src/module/division_new/ui/create_report.tsx
- src/module/division_new/ui/echart_bar_report.tsx
- src/module/division_new/ui/event_report.tsx
- src/module/division_new/ui/report_division_id.tsx
- src/module/document/ui/navbar_document_division.tsx
- src/module/project/ui/add_detail_task_project.tsx
- src/module/project/ui/add_member_detail_project.tsx
- src/module/project/ui/cancel_project.tsx
- src/module/project/ui/create_date_end_task.tsx
- src/module/project/ui/create_project.tsx
- src/module/project/ui/create_users_project.tsx
- src/module/project/ui/edit_detail_task_project.tsx
- src/module/project/ui/edit_task_project.tsx
- src/module/project/ui/tab_project.tsx
- src/module/user/profile/ui/profile.tsx
Deskripsi:
- update api
- update document
- update user profile
No issue
> feat : update featur

- src/module/announcement/ui/edit_announcement.tsx
- src/module/announcement/ui/edit_choose_member.tsx
- src/module/calender/ui/update_division_calender.tsx
- src/module/calender/ui/update_list_users.tsx
- src/module/discussion/ui/form_edit_discussion.tsx
- src/module/division_new/ui/edit_division.tsx
- src/module/position/ui/drawer_detail_position.tsx
- src/module/project/ui/add_member_detail_project.tsx
- src/module/project/ui/edit_detail_task_project.tsx
- src/module/project/ui/edit_task_project.tsx
- src/module/task/ui/add_detail_task.tsx
- src/module/task/ui/create_date_end_task.tsx
- src/module/task/ui/create_users_project.tsx
- src/module/task/ui/edit_detail_task.tsx
- src/module/task/ui/edit_task.tsx
- src/module/user/member/ui/create_member.tsx
- src/module/user/member/ui/edit_member.tsx
- src/module/user/profile/ui/edit_profile.tsx
Deskripsi:
- update announcement
- update celender
- update task
- update user
No Issue
> style : update skeleton

- src/app/api/document/route.ts
- src/app/api/document/upload/route.ts
- src/module/document/lib/api_document.ts
- src/module/document/ui/drawer_menu_document_division.tsx
Deskripsi:
- uplaod file
No Issues
> upd: dokumen divisi

- src/module/announcement/ui/create_announcement.tsx
- src/module/announcement/ui/create_users_announcement.tsx
- src/module/announcement/ui/detail_announcement.tsx
- src/module/announcement/ui/edit_announcement.tsx
- src/module/announcement/ui/edit_choose_member.tsx
- src/module/announcement/ui/list_announcement.tsx
- src/module/announcement/ui/navbar_detail_announcement.tsx
- src/module/division_new/ui/create_anggota_division.tsx
- src/module/division_new/ui/information_division.tsx
- src/module/division_new/ui/list_division.tsx
- src/module/home/ui/list_divisi.tsx
- src/module/home/ui/list_project.tsx
- src/module/project/ui/list_project.tsx
- src/module/user/member/ui/tab_list_member.tsx
Deskripsi:
- update announcement
- update home
- update home
No Issue
> style : update ui

- src/module/_global/layout/layout_modal_view_file.tsx
- src/module/project/ui/add_detail_task_project.tsx
- src/module/project/ui/add_member_detail_project.tsx
- src/module/project/ui/create_project.tsx
- src/module/project/ui/create_users_project.tsx
- src/module/project/ui/list_anggota_detail_project.tsx
- src/module/project/ui/list_project.tsx
- src/module/project/ui/list_tugas_detail_project.tsx
- src/module/task/ui/add_member_detail_task.tsx
- src/module/task/ui/create_task.tsx
Deskripsi:
- update task
No issue
> style : update responsive project

- src/app/api/project/file/[id]/route.ts
- src/app/api/project/route.ts
- src/app/api/task/file/[id]/route.ts
- src/app/api/task/route.ts
Deskripsi:
- fix api upload file pada project dan task
No Issues
> fix: upload file

- src/module/_global/layout/layout_drawer.tsx
- src/module/division_new/ui/list_document.tsx
- src/module/division_new/ui/list_task.tsx
- src/module/document/ui/navbar_document_division.tsx
Deskripsi:
- update documents
- update layout
No Issue
> style : update style

- src/app/api/discussion/[id]/route.ts
- src/app/api/discussion/route.ts
- src/module/calender/ui/create_user_calender.tsx
- src/module/calender/ui/date_event_division.tsx
- src/module/calender/ui/detail_event_division.tsx
- src/module/calender/ui/history_division_calender.tsx
- src/module/calender/ui/navbar_create_division_calender.tsx
- src/module/calender/ui/update_division_calender.tsx
- src/module/calender/ui/update_list_users.tsx
- src/module/discussion/ui/detail_discussion.tsx
- src/module/discussion/ui/form_create_discussion.tsx
- src/module/discussion/ui/form_edit_discussion.tsx
- src/module/discussion/ui/list_discussion.tsx
Deskripsi:
- update api discussion
- update calender
- update dicussion
No Issue
> style : update style responsive

- src/app/api/announcement/[id]/route.ts
- src/app/api/announcement/route.ts
- src/app/api/group/get-division/route.ts
- src/module/announcement/ui/create_announcement.tsx
- src/module/announcement/ui/navbar_announcement.tsx
- src/module/announcement/ui/navbar_detail_announcement.tsx
Deskripsi:
- pembatasan pengumuman
- fix get all
No Issues
> upd: announcement

- src/app/api/project/route.ts
- src/module/project/ui/list_project.tsx
- src/module/project/ui/menu_drawer_project.tsx
- src/module/project/ui/tab_project.tsx
Deskripsi:
- pembatasan user
No Issues
> upd: project

- src/app/api/division/[id]/member/route.ts
- src/app/api/division/[id]/route.ts
- src/app/api/task/[id]/member/route.ts
- src/module/calender/ui/create_user_calender.tsx
- src/module/calender/ui/update_list_users.tsx
- src/module/division_new/index.ts
- src/module/division_new/lib/api_division.ts
- src/module/division_new/ui/create_anggota_division.tsx
- src/module/project/ui/list_project.tsx
- src/module/task/ui/add_member_detail_task.tsx
- src/module/task/ui/create_users_project.tsx
Deskripsi:
- update api division
- update task
- update calender
No Issue
> style: update user member

- src/app/api/project/[id]/member/route.ts
- src/module/project/lib/api_project.ts
- src/module/project/ui/add_member_detail_project.tsx
- src/module/project/ui/create_users_project.tsx
Deskripsi:
- update project atau kegiatan
No Issue
> style : update style kegiatan

- src/app/(application)/project/page.tsx
- src/app/api/division/route.ts
- src/module/division_new/ui/drawer_division.tsx
- src/module/division_new/ui/information_division.tsx
- src/module/division_new/ui/list_division.tsx
- src/module/project/components/ui/drawer_project.tsx
- src/module/project/ui/list_project.tsx
- src/module/project/ui/menu_drawer_project.tsx
Deskripsi:
- pembatasan role
- project dipakein filter
No ISsues
> upd: division

- src/app/api/calender/[id]/member/route.ts
- src/module/calender/lib/api_calender.ts
- src/module/calender/lib/type_calender.ts
- src/module/calender/ui/create_user_detail_calender.tsx
- src/module/calender/ui/detail_event_division.tsx
Deskripsi:
- tambah anggota kalender dipisah aja jadinya
No Issues
> upd: calender

- src/module/announcement/ui/create_users_announcement.tsx
- src/module/announcement/ui/edit_choose_member.tsx
- src/module/division_new/ui/feature_detail_division.tsx
- src/module/project/ui/create_project.tsx
- src/module/project/ui/list_anggota_detail_project.tsx
- src/module/project/ui/list_project.tsx
- src/module/project/ui/results_file.tsx
Deskripsi:
- update announcement
- update division new
No Issue
> style : style mobile

- src/module/calender/ui/date_event_division.tsx
- src/module/division_new/ui/create_division.tsx
- src/module/division_new/ui/drawer_division.tsx
- src/module/division_new/ui/information_division.tsx
- src/module/division_new/ui/list_discussion.tsx
- src/module/document/ui/navbar_document_division.tsx
- src/module/home/ui/features.tsx
- src/module/home/ui/list_discussion.tsx
- src/module/home/ui/list_event.tsx
- src/module/home/ui/list_notification.tsx
- src/module/home/ui/view_detail_feature.tsx
- src/module/project/ui/list_anggota_detail_project.tsx
- src/module/task/ui/create_task.tsx
- src/module/task/ui/detail_list_anggota_task.tsx
- src/module/task/ui/detail_progress_task.tsx
- src/module/task/ui/drawer_division_task.tsx
Deskripsi:
- update calender
- document
- update home
- update task
No Issue
> style: update mobile

- src/app/api/user/route.ts
- src/module/_global/components/reload_button_top.tsx
- src/module/project/ui/list_tugas_detail_project.tsx
- src/module/project/ui/navbar_detail_project.tsx
- src/module/user/member/ui/edit_member.tsx
- src/module/user/member/ui/tab_list_member.tsx
- src/module/user/profile/ui/edit_profile.tsx
Deskripsi:
- update api
- update globle
- update user
- update profile
No Issue
> feat : update scroll and style

- src/app/api/discussion/route.ts
- src/app/api/division/route.ts
- src/app/api/project/route.ts
- src/app/api/task/route.ts
Deskripsi:
- update notifikasi pada create diskusi, divisi, project dan task
No Issues
> upd: notifikasi

- src/app/api/division/[id]/detail/route.ts
- src/module/division_new/lib/type_division.ts
- src/module/division_new/ui/list_document.tsx
Deskripsi:
- file terbaru pada detail divisi udh bisa langsung ke folder
No Issues
> fix: divisi dokumen

- src/app/api/version-app/route.ts
- src/app/test/_ui/RealtimePage.tsx
- src/module/_global/components/notification_custome.tsx
- src/module/_global/components/wrap_layout.tsx
- src/module/home/ui/view_home.tsx
deskripsi:
- coba realtime
- api version
No Issues
> upd: realtime

- src/app/api/version-app/route.ts
- src/module/_global/components/wrap_layout.tsx
Deskripsi:
- komen realtime
No Issues
> upd: komen

- src/app/api/announcement/route.ts
- src/app/test/_ui/RealtimePage.tsx
- src/module/_global/bin/val_global.ts
- src/module/_global/components/notification_custome.tsx
- src/module/_global/components/wrap_layout.tsx
- src/module/_global/index.ts
- src/module/announcement/ui/create_announcement.tsx
Deskripsi;
- upd realtime di halaman pengumuman
No Issues
> upd:realtime

- prisma/schema.prisma
- src/app/api/banner/[id]/route.ts
- src/app/api/banner/route.ts
- src/module/_global/bin/val_global.ts
- src/module/_global/fun/view_dir.ts
- src/module/_global/index.ts
Deskripsi:
- database table banner
- api crud banner
No
Issues
> upd: be banner

- src/module/banner/lib/api_banner.ts
Deskripsi:
- api banner No Issues
> upd: banner

- src/app/(application)/banner/edit/[id]/page.tsx
- src/module/banner/lib/api_banner.ts
- src/module/banner/lib/type_banner.ts
- src/module/banner/ui/create_banner.tsx
- src/module/banner/ui/edit_banner.tsx
- src/module/banner/ui/list_banner.tsx
> Perbaikan Banner

- src/app/(application)/banner/edit/[id]/page.tsx
- src/module/banner/index.ts
- src/module/banner/ui/create_banner.tsx
- src/module/banner/ui/edit_banner.tsx
- src/module/banner/ui/list_banner.tsx
Tambahan API Edit, Delete, List Banner dan Validasi di Edit dan Create Banner
> Tambahan API Edit, Delete, List Banner dan Validasi

- src/app/api/division/[id]/detail/route.ts
- src/app/api/home/route.ts
Deskripsi:
- fix tgl diskusi pada halaman home
- fix tgl diskusi pada halaman divisi
No Issues
> fix: tgl diskusi

- src/module/banner/ui/create_banner.tsx
- src/module/banner/ui/edit_banner.tsx
- src/module/banner/ui/list_banner.tsx
Fix API List Banner, Edit Banner, Create Banner
> Fix API List Banner, Edit Banner, Create Banner

- src/module/_global/components/skeleton_banner.tsx
- src/module/banner/ui/create_banner.tsx
- src/module/banner/ui/list_banner.tsx
> Perbaikan Di Bagian Skeleton

- src/app/api/project/[id]/route.ts
- src/app/api/version-app/route.ts
- src/module/_global/view/view_filter.tsx
- src/module/home/ui/list_project.tsx
- src/module/home/ui/view_home.tsx
- src/module/position/ui/drawer_detail_position.tsx
- src/module/position/ui/drawer_list_position.tsx
- src/module/project/ui/add_detail_task_project.tsx
- src/module/project/ui/create_date_end_task.tsx
- src/module/project/ui/edit_detail_task_project.tsx
- src/module/project/ui/edit_task_project.tsx
- src/module/task/ui/add_detail_task.tsx
- src/module/task/ui/add_file_detail_task.tsx
- src/module/task/ui/add_member_detail_task.tsx
- src/module/task/ui/cancel_task.tsx
- src/module/task/ui/create_date_end_task.tsx
- src/module/task/ui/detail_list_anggota_task.tsx
- src/module/task/ui/detail_list_file_task.tsx
- src/module/task/ui/detail_list_tugas_task.tsx
- src/module/task/ui/detail_progress_task.tsx
- src/module/task/ui/edit_detail_task.tsx
- src/module/task/ui/edit_task.tsx
Deskripsi:
- tugas divisi
- kegiatan
- home
- filter
No Issues
> fix: fixing super admin

- src/app/api/project/[id]/member/route.ts
- src/app/api/project/[id]/route.ts
- src/module/project/lib/api_project.ts
- src/module/project/ui/add_file_detail_project.tsx
- src/module/project/ui/add_member_detail_project.tsx
- src/module/project/ui/cancel_project.tsx
- src/module/project/ui/create_users_project.tsx
- src/module/project/ui/edit_detail_task_project.tsx
- src/module/project/ui/list_project.tsx
- src/module/project/ui/navbar_detail_project.tsx
- src/module/project/ui/progress_detail_project.tsx
Deskripsi:
- ganti warna sesuai temq
- pencarian anggota
- realtime edit tugas
- loading saat upload file
- order list file by created at
- tidak menampilkan anggota dg user role selain coadmin dan user pada tambah anggota project
- perbaikan link roouter tombol back pada detail project
- memberikan loading pada cancel kegiatan
No Issues
> fix: project

- src/app/api/division/report/route.ts
- src/app/api/home/route.ts
- src/app/api/user/route.ts
- src/module/division_new/ui/create_anggota_division.tsx
- src/module/division_new/ui/create_report.tsx
- src/module/division_new/ui/drawer_detail_division.tsx
- src/module/division_new/ui/echart_pai_report.tsx
- src/module/division_new/ui/edit_division.tsx
- src/module/division_new/ui/event_report.tsx
- src/module/division_new/ui/information_division.tsx
- src/module/division_new/ui/list_discussion.tsx
- src/module/division_new/ui/list_division.tsx
- src/module/division_new/ui/list_document.tsx
- src/module/division_new/ui/list_task.tsx
- src/module/division_new/ui/navbar_detail_division.tsx
- src/module/division_new/ui/report_division_id.tsx
- src/module/user/lib/type_user.ts
- src/module/user/member/lib/api_member.ts
Deskripsi:
- tampilan kosong saat list grid
- tombol back pada detail divisi
- format tgl pada input laporan divisi
- format desimal pada chart progres tugas laporan divisi
- perbaikan kata event pada laporan divisi
- perbaikan inputan grup pada laporan divisi yg hanya bisa di akses oleh super admin
- perbaikan kalimat belum ada menjadi tidak ada
- menampilkan hanya user dg role coadmin dan user aja saat tambah anggota divisi
- perbaikan pencarian
- loading saat tambah anggota
- tidak memmakai skeleton pada saat hapus dan ganti sstatus admin divisi
- saat edit berhasil maka diarahkan ke halaman detail info divisi
- perbaikan saat bilangan desimal 100.00 pada halaman home
No Issues
> fix: divisi

- src/app/api/discussion/route.ts
- src/module/discussion/ui/drawer_detail_discussion.tsx
- src/module/discussion/ui/list_discussion.tsx
Deskripsi:
- realtime
No Issues
> fix: diskusi

- src/app/api/push-notification/route.ts
- src/module/home/ui/view_detail_feature.tsx
Deskripsi:
- menambahkan button sementara pada fitur untuk mengetes push notifikasi
No Issues
> upd: cek notifikasi
